# Generated by Django 3.1.5 on 2021-01-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notepad',
            options={'verbose_name': '메모장', 'verbose_name_plural': '메모장'},
        ),
        migrations.AlterField(
            model_name='notepad',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notepad',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='notepad',
            name='title',
            field=models.CharField(max_length=128, verbose_name='제목'),
        ),
        migrations.AlterModelTable(
            name='notepad',
            table='notepad',
        ),
    ]
